import { ISignal } from '@v2/types/analyzers';

/**
 * Defines the contract for a scorer module.
 * Scorers consume signals generated by analyzers and compute a confidence score.
 *
 * @example
 * class DirectImportScorer implements IScorer {
 *   name = "direct-import";
 *   version = "1.0.0";
 *   score(signals: ISignal[]): number {
 *     return signals.reduce((acc, s) => acc + (s.matched ? s.weight : 0), 0);
 *   }
 * }
 */
export interface IScorer {
  /** Unique name of the scorer */
  name: string;
  /** Semantic version of the scorer */
  version: string;
  /**
   * Computes a score based on a list of signals.
   * @param signals The signals to analyze
   * @returns A confidence score (typically 0-1)
   */
  score(signals: ISignal[]): number;
}
